# -*- coding: utf-8 -*-
"""webscraping_ml_key_terms.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZjE_oNgZPi3zSfNiPIALZy1JHPpgS-BE
"""

from bs4 import BeautifulSoup
import requests

page = requests.get('https://developers.google.com/machine-learning/glossary')
soup = BeautifulSoup(page.text, 'html.parser')

tagList= [[tag['data-text'],tag['class'][0]] for tag in soup.findAll('h2')]
tagList

idnames = []
for i in tagList:
  if(i[1]=='hide-from-toc'):
    idnames.append(i[0])

idnames = [i.strip(' ').title() for i in idnames]

# Hurray Dictionary made today
idnames

# Create a UI to display one of them at random
import random

def gen_random_term():

	todaysWord = random.choice(idnames)
	print(f'Term of the day is {todaysWord}')

# pip install google

# search for the term on web with additional text 'in Machine learning'
def make_glossary_file():
	Dictionary = open('mlDict.csv')

def make_a_search(todaysWord):
	query =  todaysWord + 'in Machine Learning'
	from googlesearch import search
	webresults = [r for r in search(query, num=10, stop=10, pause=2)]



import webbrowser
webbrowser.get("google-chrome").open(webresults[0])